export enum Department {
  QUOTING = 'QUOTING',
  QUOTE_ACCEPTED = 'QUOTE_ACCEPTED',
  ORDER_STOCK = 'ORDER_STOCK',
  STOCK_RECEIVED = 'STOCK_RECEIVED',
  ON_DECK = 'ON_DECK',
  ON_MACHINE = 'ON_MACHINE',
  FINISHING = 'FINISHING',
  QUALITY_CONTROL = 'QUALITY_CONTROL',
  SHIPPING = 'SHIPPING',
  SHIPPED = 'SHIPPED',
}

export enum Priority {
  HIGH = 'HIGH',
  NORMAL = 'NORMAL',
  LOW = 'LOW',
}
